trigger:
- master

jobs: 
  - job: nodeExpressAzureJob
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js'
        inputs:
          versionSpec: '8.x'
      - script: |
            npm install
            npm test
      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
          includeRootFolder: false

      - task: PublishBuildArtifacts@1
        displayName: 'Publish artifacts: drop'
